version: '3.8'

services:
  bili-curator:
    build: 
      context: ./bili_curator
      args:
        VERSION: ${VERSION:-v6}
    image: bili_curator:${VERSION:-v6}
    container_name: bili_curator_${VERSION:-v6}
    ports:
      - "8080:8080"
      # STRM代理端口 (仅V7使用)
      - "${STRM_PROXY_PORT:-8081}:${STRM_PROXY_PORT:-8081}"
    volumes:
      # 本地下载目录
      - ${DOWNLOAD_HOST_PATH:-/Volumes/nas-mk/xiaoya_emby/xiaoya/bilibili}:/app/downloads
      # STRM文件目录 (V7)
      - ${STRM_HOST_PATH:-/Volumes/nas-mk/xiaoya_emby/xiaoya/bilibili_strm}:/app/strm
      # 配置目录
      - ${CONFIG_HOST_PATH:-~/bilibili_config}:/app/data
      # 日志目录
      - ${CONFIG_HOST_PATH:-~/bilibili_config}/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - VERSION=${VERSION:-v6}
      - TZ=${TZ:-Asia/Shanghai}
      
      # 基础配置
      - DOWNLOAD_PATH=/app/downloads
      - DB_PATH=/app/data/bilibili_curator.db
      - DEDUP_SCOPE=${DEDUP_SCOPE:-subscription}
      - DEDUP_SCAN_FILESYSTEM=${DEDUP_SCAN_FILESYSTEM:-0}
      - BATCH_IN_SIZE=${BATCH_IN_SIZE:-500}
      
      # STRM配置 (V7)
      - STRM_PATH=/app/strm
      - STRM_PROXY_PORT=${STRM_PROXY_PORT:-8081}
      - STRM_DEFAULT_QUALITY=${STRM_DEFAULT_QUALITY:-720p}
      - STRM_CACHE_TTL=${STRM_CACHE_TTL:-300}
      - STRM_MAX_CONCURRENT_STREAMS=${STRM_MAX_CONCURRENT_STREAMS:-10}
      - STRM_RATE_LIMIT_PER_IP=${STRM_RATE_LIMIT_PER_IP:-5}
      
      # B站认证 (STRM模式需要)
      - BILIBILI_SESSDATA=${BILIBILI_SESSDATA:-}
      - BILIBILI_BILI_JCT=${BILIBILI_BILI_JCT:-}
      - BILIBILI_BUVID3=${BILIBILI_BUVID3:-}
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "bili_curator.version=${VERSION:-v6}"
      - "bili_curator.mode=${VERSION:-v6}"
