services:
  bili-curator:
    build: .
    container_name: bili_curator_v6
    ports:
      - "8080:8080"
    volumes:
      # 下载目录绑定到Emby bilibili目录
      - /Volumes/nas-mk/xiaoya_emby/xiaoya/bilibili:/app/downloads
      # 配置目录绑定到用户家目录
      - ~/bilibili_config:/app/data
      # 日志目录
      - ~/bilibili_config/logs:/app/logs
      # 静态文件目录挂载（确保前端页面持久化）
      - ./static:/app/static:ro
      # Web前端文件挂载（确保前端界面更新）
      - ./web/dist:/app/web/dist:ro
      # 应用代码挂载（确保API和服务代码持久化）
      - ./app:/app/app:ro
      # 主应用文件挂载
      - ./main.py:/app/main.py:ro
    environment:
      - PYTHONUNBUFFERED=1
      # 设置下载路径为挂载的目录
      - DOWNLOAD_PATH=/app/downloads
      # 设置时区为上海时区
      - TZ=Asia/Shanghai
      # 使用已存在的旧数据库文件，确保迁移在该库上执行
      - DB_PATH=/app/data/bilibili_curator.db
      # 订阅维度去重与性能相关配置
      - DEDUP_SCOPE=subscription
      - DEDUP_SCAN_FILESYSTEM=0
      - BATCH_IN_SIZE=500
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
